#!/bin/sh
cat << EOF > $2
// This is an autogenerated file, do not edit!

#include "headers.h"

const std::map<const std::string, int> defines = {
EOF

grep '#define [A-Z]' $1 \
	| sed 's/.*#define \([^ \t]\+\)[ \t]\+\(.*\)/\t{"\1", \2},/' \
	>> $2

cat << EOF >> $2
};

const std::multimap<int, const std::string> reverseDefines = {
EOF

grep '#define [A-Z]' $1 \
	| sed 's/.*#define \([^ \t]\+\)[ \t]\+\(.*\)/\t{\2, "\1"},/' \
	>> $2

cat << EOF >> $2
};
EOF
